apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-MODELNAME-storage-claim
  namespace: confighubplaceholder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
