apiVersion: v1
kind: ServiceAccount
metadata:
  name: vllm-router-service-account
  namespace: confighubplaceholder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vllm-reader
  namespace: confighubplaceholder
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vllm-deployment-access-binding
  namespace: confighubplaceholder
subjects:
  - kind: ServiceAccount
    name: vllm-router-service-account
roleRef:
  kind: Role
  name: vllm-reader
  apiGroup: rbac.authorization.k8s.io
